Семантическая верстка страницы каталога
htmlacademy-htmlcss/1466459-device-29 pull request #3
Opened 2020-10-04 14:12 UTC by andreysereda1976

2020-10-04 19:43 UTC, kosovych requested changes

2020-10-04 19:43 UTC, kosovych commented on catalog.html
> +          <button class="search-button">Найти</button>
добавь type

2020-10-04 19:43 UTC, kosovych commented on catalog.html
> +			        <h3>Любительская селфи-палка</h3>
хороший патерн делать название и картинку продукта ссылкой на страницу товара

2020-10-04 19:43 UTC, kosovych commented on catalog.html
> +			    <button type="button" class="page-button back-button" disabled>Назад</button>
тоже ссылкой сделай

2020-10-05 13:33 UTC, kosovych requested changes

2020-10-05 13:33 UTC, kosovych commented on catalog.html
> +            </a>
не нужно всю карточку, только название картинку

2020-10-05 14:27 UTC, andreysereda1976 commented on catalog.html
> +            </a>
в смысле на цену не делать? тогда придется либо закрывающий /a в середину diva втыкать (так можно вообще?), либо выдергивать название из общего diva (не хотелось бы), либо отдельные ссылки вешать на картинку и на название. как лучше?

2020-10-05 18:02 UTC, merged