Стилизация главной страницы
htmlacademy-htmlcss/1466459-device-29 pull request #4
Opened 2020-10-09 20:36 UTC by andreysereda1976

2020-10-09 22:19 UTC, kosovych requested changes

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +}
я бы сделал эти картинки контентными, хотя бы потому что если нужно изменить, что придется идти в HTML, что сильно проще чем править CSS

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +}
тоже самое что и с иконками категорий

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +  width: 1440px;
лучше сделать один класс для ограничения и выравнивания контента, иначе - дублирование кода

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +
![image](https://user-images.githubusercontent.com/19348382/95635539-5b1d8c00-0a95-11eb-9360-fd8f8a7399a9.png)
нужно подтянуть

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +
![Uploading image.png…]()

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +
![image](https://user-images.githubusercontent.com/19348382/95635642-9e77fa80-0a95-11eb-86a6-b1c7dac09ea5.png)

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +
![image](https://user-images.githubusercontent.com/19348382/95635764-fd3d7400-0a95-11eb-87db-7a6e065a3b64.png)
зачем меняешь цвет по ховеру? сверь с стайгайдом

2020-10-09 22:19 UTC, kosovych commented on css/style.css
> +
нужно доделать в футере интерактивные элементы по стайлгайду

2020-10-17 16:13 UTC, andreysereda1976 commented on css/style.css
> +
переделал. по ховеру вообще ничего не надо прозрачным делать. только по нажатию

2020-10-17 16:14 UTC, andreysereda1976 commented on css/style.css
> +  width: 1440px;
в смысле - в общий для всех класс загнать display: flex, flex-direction: row и margin: 0, например?

2020-10-19 17:19 UTC, kosovych commented on css/style.css
> +
не указаны веб-безопасные шрифты

2020-10-19 17:33 UTC, kosovych requested changes

2020-10-19 17:33 UTC, kosovych commented on css/style.css
> +
https://up.htmlacademy.ru/htmlcss/29/project/device#device-3-1 - ``Фоны, которые упираются в края макета, должны тянуться на всю страницу.``
![image](https://user-images.githubusercontent.com/19348382/96490997-4a65d680-124a-11eb-81ad-bdfbec0267d2.png)

2020-10-19 18:52 UTC, merged